filter:
  paths:
    - src/
  dependency_paths:
    - vendor/
  excluded_paths:
    - src/bundle.php
build:
  nodes:
    analysis:
      tests:
        override:
          - phpcs-run --standard=psr2 src/
