language: php

stages:
  - test
  - name: deploy
    if: branch = master

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

script:
  - vendor/bin/phpunit

jobs:
  include:
    - stage: deploy
      script: .travis/mkdocs.sh
      sudo: required
