language: php

stages:
  - test
  - name: deploy
    if: branch = master

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

addons:
  apt:
    packages:
      - ca-certificates

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer global require phpstan/phpstan
  - composer install

script:
  - vendor/bin/phpcs --standard=psr2 src
  - phpstan analyse
  - vendor/bin/phpunit

jobs:
  include:
    - stage: deploy
      script: .travis/mkdocs.sh
      sudo: required
