language: php

stages:
  - test
  - name: deploy
    if: branch = master

php:
  - 7.4

addons:
  apt:
    packages:
      - ca-certificates
      - python3
      - python3-pip

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer global require phpstan/phpstan
  - composer install

before_script:
  - export PATH="$PATH:/home/travis/.composer/vendor/bin"

jobs:
  include:
    - stage: test
      script: composer lint
    - script: composer test
    - stage: deploy
      script: .travis/mkdocs.sh
