language: php

stages:
  - test
  - name: deploy
    if: branch = master

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

addons:
  apt:
    packages:
      - ca-certificates

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer global require phpstan/phpstan
  - composer install

before_script:
  - export PATH="$PATH:/home/travis/.composer/vendor/bin"

script:
  - echo $PATH
  - ls /home/travis/.composer/vendor/bin
  - composer lint
  - composer test

jobs:
  include:
    - stage: deploy
      script: .travis/mkdocs.sh
      sudo: required
