language: php

stages:
  - test
  - name: deploy
    if: branch = master

php:
  - 7.4
  - 8

addons:
  apt:
    packages:
      - ca-certificates

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install

before_script:
  - export PATH="$PATH:/home/travis/.composer/vendor/bin"

jobs:
  include:
    - script: composer lint
    - script: composer test
    - stage: deploy
      script: .travis/mkdocs.sh
